// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHjmWQlP-n73PLPWtGYmGcSw_PcnOGlR8',
    appId: '1:797505108536:web:76940775fab36191fa04cd',
    messagingSenderId: '797505108536',
    projectId: 'sqlite-student-app',
    authDomain: 'sqlite-student-app.firebaseapp.com',
    storageBucket: 'sqlite-student-app.firebasestorage.app',
    measurementId: 'G-4DCWNNLG0X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA6GvYlnmmm3jwQ3w6IhDr2DKnn-5LRfH0',
    appId: '1:797505108536:android:c39bb67c6f727e89fa04cd',
    messagingSenderId: '797505108536',
    projectId: 'sqlite-student-app',
    storageBucket: 'sqlite-student-app.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtYamFVb3l14xLfH6d8zE7gvdfMsG1PrM',
    appId: '1:797505108536:ios:2f22919088ed8e9ffa04cd',
    messagingSenderId: '797505108536',
    projectId: 'sqlite-student-app',
    storageBucket: 'sqlite-student-app.firebasestorage.app',
    iosBundleId: 'com.example.sqliteApp',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtYamFVb3l14xLfH6d8zE7gvdfMsG1PrM',
    appId: '1:797505108536:ios:2f22919088ed8e9ffa04cd',
    messagingSenderId: '797505108536',
    projectId: 'sqlite-student-app',
    storageBucket: 'sqlite-student-app.firebasestorage.app',
    iosBundleId: 'com.example.sqliteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHjmWQlP-n73PLPWtGYmGcSw_PcnOGlR8',
    appId: '1:797505108536:web:7904e3bd27c18625fa04cd',
    messagingSenderId: '797505108536',
    projectId: 'sqlite-student-app',
    authDomain: 'sqlite-student-app.firebaseapp.com',
    storageBucket: 'sqlite-student-app.firebasestorage.app',
    measurementId: 'G-BS6H37BEE0',
  );
}
